"""Fleet-wide operator token: one key, generated by the console, pushed into
every client instance's `.env` over SSH, and stored once in the console's own
config (clients.json) so managed-field config writes authenticate automatically
— no per-instance key to remember.

Why this exists: managed fields (voice, LLM/STT providers, models) can only be
written through the running app's admin API with a matching X-Operator-Token
(see the instance's backend/config.py managed_mode/operator_token). Setting that
token by hand on every box, and keeping the console in sync, doesn't scale past
a handful of clients. This module makes it one button: generate → push to all →
store → (rotate = do it again with a fresh key).

Reuses the trusted plumbing rather than reinventing it:
  - env_tool.read_remote_env / write_remote_env — the same SSH `.env` path the
    Credentials tool uses (backs the file up first, base64 over the wire, no
    shell-escaping hazards). We READ first and MERGE so no other secret is lost.
  - the same override-aware, app-ONLY `docker compose up -d` scoping deploy_client
    uses — a satellite instance never touches the shared caddy container.

Safety notes:
  - Recreating (not just restarting) the app is required: an env-var change is
    only picked up when the container is recreated. `up -d` recreates only
    containers whose config changed.
  - Rotation stores the new key even if some pushes fail. The console must use
    the value it just tried to install fleet-wide; any instance that failed the
    push keeps the OLD key and is reported so it can be retried. You are never
    locked out — SSH still works regardless of the operator token.
  - The key is never returned to the browser. Callers get per-instance ok/error
    and a boolean "configured", never the secret itself.
"""
from __future__ import annotations

import secrets
from typing import Any

from backend import config as cfg
from backend import core
from backend import env_tool

_ENV_KEY = "OPERATOR_TOKEN"


def generate_key() -> str:
    """A long, URL-safe random secret. token_urlsafe(32) → ~43 chars, ample
    entropy, and safe as a bare (unquoted) value in a KEY=VALUE .env line."""
    return secrets.token_urlsafe(32)


def is_configured() -> bool:
    """True when a fleet operator token is stored in the console (never
    reveals the value)."""
    return bool(cfg.load_operator_token())


def _recreate_app(ssh_target: str, remote_dir: str) -> tuple[bool, str]:
    """`docker compose up -d` so the new .env is loaded — override-aware and
    scoped to the `app` service on satellites (an override file present means
    a shared-VPS satellite whose bare `up` would collide with the shared
    dental-agent-caddy container; see core.deploy_client). No git pull / build,
    just recreate."""
    shell_dir = core._shell_remote_dir((remote_dir or "").rstrip("/"))
    project = core._project_name(shell_dir)
    compose_file = f"{shell_dir}/docker-compose.yml"
    override_file = f"{shell_dir}/docker-compose.override.yml"
    cmd = (
        f"if [ -f {override_file} ]; then "
        f"compose_files=\"-p {project} -f {compose_file} -f {override_file}\"; service_scope=\"app\"; "
        f"else compose_files=\"-p {project} -f {compose_file}\"; service_scope=\"\"; fi; "
        f"cd {shell_dir} && docker compose $compose_files up -d $service_scope 2>&1"
    )
    return core.run_ssh(ssh_target, cmd, timeout=core.DEPLOY_TIMEOUT)


def push_to_client(client: dict[str, Any], token: str) -> dict[str, Any]:
    """Install `token` as OPERATOR_TOKEN in one client's .env (preserving every
    other key) and recreate its app so it loads. Never raises — failures come
    back in the result dict with the stage that failed."""
    name = client.get("name", "?")
    ssh_target = client.get("ssh_target") or ""
    remote_dir = (client.get("remote_dir") or "").rstrip("/")
    if not ssh_target or not remote_dir:
        return {"name": name, "ok": False, "stage": "config",
                "error": "no ssh_target/remote_dir configured"}

    read = env_tool.read_remote_env(ssh_target, remote_dir)
    if not read.get("ok"):
        return {"name": name, "ok": False, "stage": "read_env",
                "error": read.get("error") or "could not read .env"}

    env = dict(read.get("env") or {})
    if env.get(_ENV_KEY) == token:
        # Already correct on disk; still recreate so a half-applied prior run
        # (written but never recreated) actually takes effect.
        pass
    env[_ENV_KEY] = token

    write = env_tool.write_remote_env(ssh_target, remote_dir, env)
    if not write.get("ok"):
        return {"name": name, "ok": False, "stage": "write_env",
                "error": write.get("error") or "could not write .env"}

    ok, out = _recreate_app(ssh_target, remote_dir)
    if not ok:
        return {"name": name, "ok": False, "stage": "recreate",
                "error": (out or "").strip()[-500:] or "recreate failed"}
    return {"name": name, "ok": True, "stage": "done", "error": None}


def rotate(clients: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Generate a NEW key, push it to every client (sequentially — a rolling,
    few-seconds-each app recreate), then store it in the console config so
    future managed-field writes use it. Stores the key regardless of per-client
    failures (see module docstring). Returns a summary WITHOUT the key."""
    token = generate_key()
    targets = clients if clients is not None else cfg.load_clients()
    results = [push_to_client(c, token) for c in targets]
    cfg.save_operator_token(token)
    pushed = sum(1 for r in results if r.get("ok"))
    return {
        "ok": bool(results) and pushed == len(results),
        "configured": True,
        "pushed": pushed,
        "total": len(results),
        "failed": [r for r in results if not r.get("ok")],
        "results": results,
    }


def push_existing(clients: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Push the ALREADY-STORED key to instances without minting a new one — for
    retrying instances that failed a rotation, or seeding a freshly onboarded
    client, without disturbing the ones already in sync. No-op (error) if no key
    is stored yet."""
    token = cfg.load_operator_token()
    if not token:
        return {"ok": False, "configured": False,
                "error": "no operator key stored yet — rotate first to mint one"}
    targets = clients if clients is not None else cfg.load_clients()
    results = [push_to_client(c, token) for c in targets]
    pushed = sum(1 for r in results if r.get("ok"))
    return {
        "ok": bool(results) and pushed == len(results),
        "configured": True,
        "pushed": pushed,
        "total": len(results),
        "failed": [r for r in results if not r.get("ok")],
        "results": results,
    }
